name: sidecar
description: "Sidecar App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: 4.11.2
  go_router: 14.8.1
  window_manager: 0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/ic_chrome_close.png
    - assets/icons/ic_chrome_maximize.png
    - assets/icons/ic_chrome_minimize.png
    - assets/icons/ic_chrome_unmaximize.png
