name: sidecar
description: "Sidecar App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  crypto: 3.0.6
  file_selector: 1.0.3
  fluent_ui: 4.11.2
  flutter_svg: 2.0.17
  go_router: 14.8.1
  window_manager: 0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
