name: sidecar
version: 0.1.0
description: "Sidecar App"

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  path: 1.9.1
  crypto: 3.0.6
  file_selector: 1.0.3
  fluent_ui: 4.12.0
  flutter_svg: 2.1.0
  go_router: 15.1.2
  window_manager: 0.5.0
  x509: 0.2.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  assets:
    - assets/icons/
  uses-material-design: true 